version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd src
      - npm ci

  build:
    commands:
      - npm run build
      - npx cdk synth

artifacts:
  files:
    - cdk.out/**/*
  base-directory: src
  discard-paths: no